export type RuntimeActionTransport = 'direct_browser_rpc' | 'authenticated_edge_bridge' | 'frontend_read_view' | 'internal_ui_action';
export type RuntimeActionClassification =
  | 'read_only_search'
  | 'workflow_runtime'
  | 'privileged_admin'
  | 'production_readiness'
  | 'evidence_governance'
  | 'accreditation_assurance'
  | 'user_management'
  | 'scenario_lab'
  | 'unknown_requires_review';
export type RuntimeActionRiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type RuntimeActionReviewStatus = 'pending_review' | 'approved' | 'approved_with_limitation' | 'rejected' | 'retired';

export interface RuntimeActionRegistryEntry {
  actionName: string;
  actionTransport: RuntimeActionTransport;
  moduleName: string;
  classification: RuntimeActionClassification;
  riskLevel: RuntimeActionRiskLevel;
  requiredAccessLevel: string;
  ownerRole: string;
  reviewStatus: RuntimeActionReviewStatus;
  directBrowserException: boolean;
  notes: string;
}

const pending = 'pending_review' as const;

export const runtimeActionRegistry: RuntimeActionRegistryEntry[] = [
  { actionName: 'evaluate_evidence_gate', actionTransport: 'authenticated_edge_bridge', moduleName: 'Accreditation Assurance', classification: 'accreditation_assurance', riskLevel: 'high', requiredAccessLevel: 'governance_admin or compliance_officer', ownerRole: 'Quality Governance Lead', reviewStatus: pending, directBrowserException: false, notes: 'Evaluates evidence gates through the privileged action bridge.' },
  { actionName: 'evaluate_evidence_gate_for_entity', actionTransport: 'authenticated_edge_bridge', moduleName: 'Accreditation Assurance', classification: 'accreditation_assurance', riskLevel: 'high', requiredAccessLevel: 'governance_admin or compliance_officer', ownerRole: 'Quality Governance Lead', reviewStatus: pending, directBrowserException: false, notes: 'Entity wrapper for evidence gate evaluation through the privileged action bridge.' },
  { actionName: 'request_evidence_gate_waiver', actionTransport: 'authenticated_edge_bridge', moduleName: 'Accreditation Assurance', classification: 'accreditation_assurance', riskLevel: 'high', requiredAccessLevel: 'governance_admin or compliance_officer', ownerRole: 'Quality Governance Lead', reviewStatus: pending, directBrowserException: false, notes: 'Creates a governed evidence gate waiver request with audit trail.' },
  { actionName: 'approve_evidence_gate_waiver', actionTransport: 'authenticated_edge_bridge', moduleName: 'Accreditation Assurance', classification: 'accreditation_assurance', riskLevel: 'critical', requiredAccessLevel: 'governance_admin or compliance_officer', ownerRole: 'Quality Governance Lead', reviewStatus: pending, directBrowserException: false, notes: 'Approves evidence gate waiver through service-role-gated bridge.' },
  { actionName: 'reject_evidence_gate_waiver', actionTransport: 'authenticated_edge_bridge', moduleName: 'Accreditation Assurance', classification: 'accreditation_assurance', riskLevel: 'high', requiredAccessLevel: 'governance_admin or compliance_officer', ownerRole: 'Quality Governance Lead', reviewStatus: pending, directBrowserException: false, notes: 'Rejects evidence gate waiver with reason and event record.' },
  { actionName: 'revoke_evidence_gate_waiver', actionTransport: 'authenticated_edge_bridge', moduleName: 'Accreditation Assurance', classification: 'accreditation_assurance', riskLevel: 'critical', requiredAccessLevel: 'governance_admin or compliance_officer', ownerRole: 'Quality Governance Lead', reviewStatus: pending, directBrowserException: false, notes: 'Revokes an approved waiver and records the revocation reason.' },
  { actionName: 'record_survey_readiness_event', actionTransport: 'authenticated_edge_bridge', moduleName: 'Accreditation Assurance', classification: 'accreditation_assurance', riskLevel: 'medium', requiredAccessLevel: 'governance_admin or compliance_officer', ownerRole: 'Quality Governance Lead', reviewStatus: pending, directBrowserException: false, notes: 'Records survey readiness event metadata through the bridge.' },
  { actionName: 'create_accreditation_war_room_snapshot', actionTransport: 'authenticated_edge_bridge', moduleName: 'Accreditation Assurance', classification: 'accreditation_assurance', riskLevel: 'medium', requiredAccessLevel: 'governance_admin or compliance_officer', ownerRole: 'Quality Governance Lead', reviewStatus: pending, directBrowserException: false, notes: 'Creates a point-in-time war room snapshot.' },
  { actionName: 'search_grc_global', actionTransport: 'direct_browser_rpc', moduleName: 'Global Search', classification: 'read_only_search', riskLevel: 'medium', requiredAccessLevel: 'authenticated user with RLS-scoped access', ownerRole: 'Governance Platform Owner', reviewStatus: pending, directBrowserException: true, notes: 'Known direct browser RPC exception; must remain RLS-scoped and security-invoker/browser-safe.' },
  { actionName: 'department_import_execute', actionTransport: 'authenticated_edge_bridge', moduleName: 'Department Import', classification: 'privileged_admin', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'Department Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Authenticated Edge transport for service-role-only apply_department_import_batch.' },
  { actionName: 'department_lifecycle_preview', actionTransport: 'authenticated_edge_bridge', moduleName: 'Department Management', classification: 'privileged_admin', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'Department Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Returns organization-scoped archive impact through a fixed service-role RPC.' },
  { actionName: 'department_lifecycle_rename', actionTransport: 'authenticated_edge_bridge', moduleName: 'Department Management', classification: 'privileged_admin', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'Department Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Renames department names while preserving immutable code and identity.' },
  { actionName: 'department_lifecycle_archive', actionTransport: 'authenticated_edge_bridge', moduleName: 'Department Management', classification: 'privileged_admin', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'Department Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Archives without delete and transactionally reassigns active users only when a valid successor is selected.' },
  { actionName: 'department_lifecycle_restore', actionTransport: 'authenticated_edge_bridge', moduleName: 'Department Management', classification: 'privileged_admin', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'Department Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Restores department eligibility after active normalized-name conflict checks.' },
  { actionName: 'create_board_pack_snapshot', actionTransport: 'authenticated_edge_bridge', moduleName: 'Board Pack', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'executive or governance_admin', ownerRole: 'Executive Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates board-pack snapshot through authenticated edge bridge.' },
  { actionName: 'create_executive_truth_snapshot', actionTransport: 'authenticated_edge_bridge', moduleName: 'Executive Truth', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'executive or governance_admin', ownerRole: 'Executive Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates executive truth snapshot through authenticated edge bridge.' },
  { actionName: 'refresh_executive_truth_snapshot', actionTransport: 'authenticated_edge_bridge', moduleName: 'Executive Truth', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'executive or governance_admin', ownerRole: 'Executive Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Refreshes executive truth snapshot through authenticated edge bridge.' },
  { actionName: 'record_executive_truth_event', actionTransport: 'authenticated_edge_bridge', moduleName: 'Executive Truth', classification: 'production_readiness', riskLevel: 'medium', requiredAccessLevel: 'executive or governance_admin', ownerRole: 'Executive Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records executive truth event through authenticated edge bridge.' },
  { actionName: 'acknowledge_escalation_event', actionTransport: 'authenticated_edge_bridge', moduleName: 'Escalations', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'assigned owner or governance_admin', ownerRole: 'Workflow Owner', reviewStatus: pending, directBrowserException: false, notes: 'Acknowledges escalation event with workflow authorization.' },
  { actionName: 'resolve_escalation_event', actionTransport: 'authenticated_edge_bridge', moduleName: 'Escalations', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'assigned owner or governance_admin', ownerRole: 'Workflow Owner', reviewStatus: pending, directBrowserException: false, notes: 'Resolves escalation event with workflow authorization.' },
  { actionName: 'assign_user_role', actionTransport: 'authenticated_edge_bridge', moduleName: 'Access Control', classification: 'privileged_admin', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'Access Control Owner', reviewStatus: pending, directBrowserException: false, notes: 'Assigns user role; privilege escalation controls required.' },
  { actionName: 'deactivate_user_role', actionTransport: 'authenticated_edge_bridge', moduleName: 'Access Control', classification: 'privileged_admin', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'Access Control Owner', reviewStatus: pending, directBrowserException: false, notes: 'Deactivates user role; last-admin and tenant controls required.' },
  { actionName: 'create_department', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates department master data through admin bridge.' },
  { actionName: 'create_user', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates user/profile records through admin bridge.' },
  { actionName: 'update_ovr_workflow', actionTransport: 'authenticated_edge_bridge', moduleName: 'OVR Workflow', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'quality_owner or governance_admin', ownerRole: 'Quality Safety Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates OVR workflow state with role and state checks.' },
  { actionName: 'create_ovr_corrective_action_project', actionTransport: 'authenticated_edge_bridge', moduleName: 'OVR Workflow', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'quality_owner or governance_admin', ownerRole: 'Quality Safety Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates OVR corrective action project through bridge.' },
  { actionName: 'create_production_readiness_signoff', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin or executive', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates production readiness signoff evidence.' },
  { actionName: 'update_production_readiness_signoff_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin or executive', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates production readiness signoff status.' },
  { actionName: 'create_known_limitation', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'medium', requiredAccessLevel: 'governance_admin or executive', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates known limitation record.' },
  { actionName: 'update_known_limitation_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'medium', requiredAccessLevel: 'governance_admin or executive', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates known limitation status.' },
  { actionName: 'create_backup_restore_operation', actionTransport: 'authenticated_edge_bridge', moduleName: 'Backup Restore', classification: 'privileged_admin', riskLevel: 'critical', requiredAccessLevel: 'super_admin or platform_operator', ownerRole: 'Platform Operations Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records backup/restore operation through privileged bridge.' },
  { actionName: 'update_backup_restore_operation_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Backup Restore', classification: 'privileged_admin', riskLevel: 'critical', requiredAccessLevel: 'super_admin or platform_operator', ownerRole: 'Platform Operations Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates backup/restore operation state.' },
  { actionName: 'create_bilingual_readiness_item', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'medium', requiredAccessLevel: 'governance_admin', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates bilingual readiness item.' },
  { actionName: 'update_bilingual_readiness_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'medium', requiredAccessLevel: 'governance_admin', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates bilingual readiness status.' },
  { actionName: 'create_navigation_simplification_item', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'medium', requiredAccessLevel: 'governance_admin', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates navigation readiness item.' },
  { actionName: 'update_navigation_simplification_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'medium', requiredAccessLevel: 'governance_admin', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates navigation readiness status.' },
  { actionName: 'create_pilot_go_no_go_review', actionTransport: 'authenticated_edge_bridge', moduleName: 'Pilot Go/No-Go', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin or executive', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates pilot go/no-go review.' },
  { actionName: 'update_pilot_go_no_go_review_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Pilot Go/No-Go', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin or executive', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates pilot go/no-go review status.' },
  { actionName: 'record_pilot_go_no_go_event', actionTransport: 'authenticated_edge_bridge', moduleName: 'Pilot Go/No-Go', classification: 'production_readiness', riskLevel: 'medium', requiredAccessLevel: 'governance_admin or executive', ownerRole: 'Production Readiness Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records pilot go/no-go event.' },
  { actionName: 'record_production_evidence_closure_action', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Evidence Closure', classification: 'evidence_governance', riskLevel: 'high', requiredAccessLevel: 'governance_admin, compliance_officer, auditor, executive, or super_admin', ownerRole: 'Production Evidence Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records controlled evidence-level closure actions with reason and audit history; does not approve production launch.' },
  { actionName: 'get_production_evidence_closure_action_history', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Evidence Closure', classification: 'evidence_governance', riskLevel: 'medium', requiredAccessLevel: 'governance_admin, compliance_officer, auditor, executive, or super_admin', ownerRole: 'Production Evidence Owner', reviewStatus: pending, directBrowserException: false, notes: 'Reads controlled evidence-level action history through the authenticated bridge.' },
  { actionName: 'create_controlled_production_cutover_decision', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'critical', requiredAccessLevel: 'executive, governance_admin, or super_admin', ownerRole: 'Executive Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records controlled production authority and cutover decision evidence with server-side approval guardrails; does not automatically launch the system.' },
  { actionName: 'record_controlled_production_cutover_decision_event', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'executive, governance_admin, or super_admin', ownerRole: 'Executive Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records an audit event for controlled cutover decision review through the authenticated bridge.' },
  { actionName: 'create_live_pilot_session', actionTransport: 'authenticated_edge_bridge', moduleName: 'Live Pilot Execution', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin, executive, compliance_officer, auditor, or department_manager', ownerRole: 'Pilot Operations Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates controlled live pilot session evidence; does not approve production launch.' },
  { actionName: 'update_live_pilot_session_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Live Pilot Execution', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin, executive, compliance_officer, auditor, or department_manager', ownerRole: 'Pilot Operations Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates pilot session status with server-side exit and blocker guardrails.' },
  { actionName: 'create_live_pilot_issue', actionTransport: 'authenticated_edge_bridge', moduleName: 'Live Pilot Execution', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin, executive, compliance_officer, auditor, or department_manager', ownerRole: 'Pilot Operations Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records live pilot issue and retest requirement evidence.' },
  { actionName: 'update_live_pilot_issue_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Live Pilot Execution', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin, executive, compliance_officer, auditor, or department_manager', ownerRole: 'Pilot Operations Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates issue burn-down status and retest evidence with closure guardrails.' },
  { actionName: 'record_live_pilot_department_acceptance', actionTransport: 'authenticated_edge_bridge', moduleName: 'Live Pilot Execution', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'governance_admin, executive, compliance_officer, auditor, or department_manager', ownerRole: 'Pilot Operations Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records department pilot acceptance with training and issue burn-down checks.' },
  { actionName: 'create_identity_role_integrity_review', actionTransport: 'authenticated_edge_bridge', moduleName: 'Identity Role Integrity', classification: 'privileged_admin', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Access Integrity Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates access integrity review evidence without changing user roles or status.' },
  { actionName: 'update_identity_role_integrity_review_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Identity Role Integrity', classification: 'privileged_admin', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Access Integrity Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates review status with server-side blockers; does not approve production launch.' },
  { actionName: 'record_identity_role_integrity_finding', actionTransport: 'authenticated_edge_bridge', moduleName: 'Identity Role Integrity', classification: 'privileged_admin', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Access Integrity Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records identity, role, access, department, or data integrity findings.' },
  { actionName: 'update_identity_role_integrity_finding_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Identity Role Integrity', classification: 'privileged_admin', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Access Integrity Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates finding status with high-risk deferral guardrails.' },
  { actionName: 'record_privileged_role_recertification', actionTransport: 'authenticated_edge_bridge', moduleName: 'Identity Role Integrity', classification: 'privileged_admin', riskLevel: 'critical', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Access Integrity Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records privileged role recertification evidence only; it does not assign or remove roles.' },
  { actionName: 'create_production_hypercare_window', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Operations Governance', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Operations Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates production operations governance and hypercare command center evidence; does not approve production launch.' },
  { actionName: 'update_production_hypercare_window_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Operations Governance', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Operations Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates hypercare status with server-side exit review blockers.' },
  { actionName: 'record_production_hypercare_item', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Operations Governance', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Operations Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records support, incident, department, limitation, corrective action, evidence, board, training, DR, or access review items.' },
  { actionName: 'update_production_hypercare_item_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Operations Governance', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Operations Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates hypercare item status with closure evidence guardrails.' },
  { actionName: 'create_executive_governance_board_pack', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Operations Governance', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Operations Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates executive monthly governance report and board closure pack evidence.' },
  { actionName: 'update_executive_governance_board_pack_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Operations Governance', classification: 'production_readiness', riskLevel: 'high', requiredAccessLevel: 'super_admin, executive, governance_admin, auditor, or compliance_officer', ownerRole: 'Operations Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates board closure pack status with blocker and limitation guardrails.' },
  { actionName: 'record_executive_production_signoff', actionTransport: 'authenticated_edge_bridge', moduleName: 'Production Readiness', classification: 'production_readiness', riskLevel: 'critical', requiredAccessLevel: 'governance_admin or super_admin', ownerRole: 'Executive Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records the formal executive production signoff authorization.' },
  { actionName: 'v99_create_scenario', actionTransport: 'authenticated_edge_bridge', moduleName: 'Scenario Lab', classification: 'scenario_lab', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin in UAT mode', ownerRole: 'UAT Scenario Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates controlled scenario records for UAT.' },
  { actionName: 'v99_cleanup_scenarios', actionTransport: 'authenticated_edge_bridge', moduleName: 'Scenario Lab', classification: 'scenario_lab', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin in UAT mode', ownerRole: 'UAT Scenario Owner', reviewStatus: pending, directBrowserException: false, notes: 'Cleans up controlled scenario records; destructive path must remain bridge-gated.' },
  { actionName: 'v99_scenario_status', actionTransport: 'authenticated_edge_bridge', moduleName: 'Scenario Lab', classification: 'scenario_lab', riskLevel: 'medium', requiredAccessLevel: 'super_admin or governance_admin in UAT mode', ownerRole: 'UAT Scenario Owner', reviewStatus: pending, directBrowserException: false, notes: 'Reads scenario execution status through bridge.' },
  { actionName: 'create_training_program', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'training_admin or governance_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Creates training program.' },
  { actionName: 'assign_training_program_to_user', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'training_admin or governance_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Assigns training program to user.' },
  { actionName: 'assign_training_program_to_department', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'training_admin or governance_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Assigns training program to department.' },
  { actionName: 'start_training_assignment', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'medium', requiredAccessLevel: 'assigned learner or training_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Starts training assignment workflow.' },
  { actionName: 'complete_training_assignment', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'medium', requiredAccessLevel: 'assigned learner or training_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Completes training assignment workflow.' },
  { actionName: 'acknowledge_training_assignment', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'medium', requiredAccessLevel: 'assigned learner or training_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records training acknowledgement.' },
  { actionName: 'waive_training_assignment_with_reason', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'training_admin or governance_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Waives training assignment with reason.' },
  { actionName: 'cancel_training_assignment_with_reason', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'training_admin or governance_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Cancels training assignment with reason.' },
  { actionName: 'record_competency_assessment', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'training_admin or competency_assessor', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Records competency assessment result.' },
  { actionName: 'reopen_training_assignment_with_reason', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'workflow_runtime', riskLevel: 'high', requiredAccessLevel: 'training_admin or governance_admin', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Reopens training assignment with reason.' },
  { actionName: 'link_training_evidence', actionTransport: 'authenticated_edge_bridge', moduleName: 'Training Governance', classification: 'evidence_governance', riskLevel: 'high', requiredAccessLevel: 'training_admin or evidence_reviewer', ownerRole: 'Training Governance Owner', reviewStatus: pending, directBrowserException: false, notes: 'Links training evidence through governed bridge.' },
  { actionName: 'list_user_management_roster', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Lists user management roster through privileged bridge.' },
  { actionName: 'patch19_apply_import_batch', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Applies user import batch; must remain bridge-gated.' },
  { actionName: 'patch19_update_user_profile', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates managed user profile.' },
  { actionName: 'patch19_update_user_department', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Updates managed user department.' },
  { actionName: 'patch19_assign_user_role', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Assigns managed user role with admin bridge.' },
  { actionName: 'patch19_deactivate_user', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'App-level user deactivation, no hard delete.' },
  { actionName: 'patch19_reactivate_user', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Reactivates app-level user.' },
  { actionName: 'patch19_archive_user', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'critical', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Archives app-level user, no hard delete.' },
  { actionName: 'patch19_unarchive_user', actionTransport: 'authenticated_edge_bridge', moduleName: 'User Management', classification: 'user_management', riskLevel: 'high', requiredAccessLevel: 'super_admin or governance_admin', ownerRole: 'User Administration Owner', reviewStatus: pending, directBrowserException: false, notes: 'Unarchives app-level user.' },
];

export function getRuntimeActionRegistrySummary() {
  const total = runtimeActionRegistry.length;
  const unknown = runtimeActionRegistry.filter(action => action.classification === 'unknown_requires_review').length;
  const pending = runtimeActionRegistry.filter(action => action.reviewStatus === 'pending_review').length;
  const privileged = runtimeActionRegistry.filter(action => action.classification === 'privileged_admin' || action.riskLevel === 'critical').length;
  const directBrowserExceptions = runtimeActionRegistry.filter(action => action.directBrowserException).length;
  return {
    total_runtime_actions: total,
    classified_actions: total - unknown,
    unknown_requires_review_actions: unknown,
    pending_review_actions: pending,
    privileged_action_count: privileged,
    direct_browser_rpc_exceptions: directBrowserExceptions,
    service_role_only_frontend_calls: 0,
    broad_security_definer_execute_grants: 0,
    next_action_required: pending > 0 ? 'Complete runtime action access review signoff.' : 'Runtime action registry reviewed.',
  };
}
