Write-Host "Applying v17.0 Enterprise Risk Management Execution Pack..."
Write-Host "Files are already arranged in repository-root paths: src/, scripts/, release/."
Write-Host "If you extracted this ZIP into the repository root, the replacement files are already in place."
node scripts/v170-install-package-scripts.mjs
Write-Host "v17.0 patch applied. Now run:"
Write-Host "npm ci"
Write-Host "npm run typecheck"
Write-Host "npm run build"
Write-Host "npm run pilot:v170-enterprise-risk"
Write-Host "npm run proof:all"
