Write-Host "Applying v22.0 Control Testing + CAPA Execution Engine Pack..."
Write-Host "Files are already arranged in repository-root paths: src/, scripts/, release/, supabase/."
Write-Host "If you extracted this ZIP into the repository root, new files are already in place."
node scripts/v220-install-package-scripts.mjs
Write-Host "v22.0 patch applied. Now run:"
Write-Host "npm ci"
Write-Host "npm run typecheck"
Write-Host "npm run build"
Write-Host "npm run pilot:v220-control-testing"
Write-Host "npm run proof:all"
