Write-Host "Applying v15.0 Audit Program Execution Pack..."
Write-Host "Files are arranged in repository-root paths: src/, scripts/, release/."
Write-Host "If you extracted this ZIP into the repository root and accepted file replacement, the files are already in place."
node scripts/v150-install-package-scripts.mjs
Write-Host "v15.0 patch applied. Now run:"
Write-Host "npm ci"
Write-Host "npm run typecheck"
Write-Host "npm run build"
Write-Host "npm run pilot:v150-audit-program"
Write-Host "npm run proof:all"
