import { useState } from 'react';
import { useI18n } from '../../i18n/I18nContext';
import type { SopDefinition } from '../../lib/policySopApi';
import { Plus, Trash2, ArrowUp, ArrowDown, Copy, BookA, HelpCircle } from 'lucide-react';

interface SopDefinitionsBuilderProps {
  definitions: SopDefinition[];
  onChange: (definitions: SopDefinition[]) => void;
  readOnly?: boolean;
}

export function SopDefinitionsBuilder({
  definitions,
  onChange,
  readOnly = false,
}: SopDefinitionsBuilderProps) {
  const { t } = useI18n();

  const handleAddDefinition = () => {
    if (readOnly) return;
    const newSeq = definitions.length + 1;
    const newDef: SopDefinition = {
      sequence_number: newSeq,
      term_en: '',
      term_ar: '',
      abbreviation: '',
      definition_en: '',
      definition_ar: '',
    };
    onChange([...definitions, newDef]);
  };

  const handleDuplicateDefinition = (index: number) => {
    if (readOnly) return;
    const target = definitions[index];
    const duplicated: SopDefinition = {
      ...target,
      id: undefined, // Fresh identity generated by backend
      term_en: target.term_en ? `${target.term_en} (Copy)` : '',
      sequence_number: index + 2,
    };

    const newDefs = [
      ...definitions.slice(0, index + 1),
      duplicated,
      ...definitions.slice(index + 1),
    ].map((def, idx) => ({
      ...def,
      sequence_number: idx + 1,
    }));

    onChange(newDefs);
  };

  const handleDeleteDefinition = (index: number) => {
    if (readOnly) return;
    const newDefs = definitions
      .filter((_, idx) => idx !== index)
      .map((def, idx) => ({
        ...def,
        sequence_number: idx + 1,
      }));
    onChange(newDefs);
  };

  const handleMoveUp = (index: number) => {
    if (readOnly || index === 0) return;
    const newDefs = [...definitions];
    const temp = newDefs[index - 1];
    newDefs[index - 1] = newDefs[index];
    newDefs[index] = temp;

    const resequenced = newDefs.map((def, idx) => ({
      ...def,
      sequence_number: idx + 1,
    }));
    onChange(resequenced);
  };

  const handleMoveDown = (index: number) => {
    if (readOnly || index === definitions.length - 1) return;
    const newDefs = [...definitions];
    const temp = newDefs[index + 1];
    newDefs[index + 1] = newDefs[index];
    newDefs[index] = temp;

    const resequenced = newDefs.map((def, idx) => ({
      ...def,
      sequence_number: idx + 1,
    }));
    onChange(resequenced);
  };

  const handleUpdateDefinition = (index: number, updates: Partial<SopDefinition>) => {
    if (readOnly) return;
    const newDefs = definitions.map((def, idx) => {
      if (idx === index) {
        return { ...def, ...updates };
      }
      return def;
    });
    onChange(newDefs);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pb-4 border-b border-slate-800">
        <div>
          <h3 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <span>{t('sop.definitions.title', 'Definitions & Abbreviations')}</span>
            <span className="px-2 py-0.5 text-xs font-medium rounded bg-indigo-950 text-indigo-300 border border-indigo-800/50">
              {definitions.length} {t('sop.definitions.count', 'Entries')}
            </span>
          </h3>
          <p className="text-xs text-slate-400 mt-1">
            {t('sop.definitions.subtitle', 'Clarify specialized medical, clinical, and operational terminology and abbreviations used throughout this SOP.')}
          </p>
        </div>

        {!readOnly && (
          <button
            type="button"
            onClick={handleAddDefinition}
            className="inline-flex items-center justify-center gap-2 px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-lg shadow transition-colors active:scale-95 shrink-0"
          >
            <Plus className="w-4 h-4" />
            <span>{t('sop.definitions.addEntry', 'Add Definition / Abbreviation')}</span>
          </button>
        )}
      </div>

      {/* Empty State */}
      {definitions.length === 0 ? (
        <div className="p-8 text-center bg-slate-900/30 rounded-xl border border-dashed border-slate-800">
          <BookA className="w-10 h-10 text-slate-600 mx-auto mb-2 stroke-[1.5]" />
          <p className="text-sm font-medium text-slate-300">
            {t('sop.definitions.noEntries', 'No definitions or abbreviations configured')}
          </p>
          <p className="text-xs text-slate-500 mt-1 max-w-md mx-auto">
            {t('sop.definitions.noEntriesPrompt', 'Add structured acronyms and terminology to ensure clinical comprehension across all performing staff.')}
          </p>
          {!readOnly && (
            <button
              type="button"
              onClick={handleAddDefinition}
              className="mt-4 inline-flex items-center gap-2 px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-lg transition-colors"
            >
              <Plus className="w-4 h-4" />
              <span>{t('sop.definitions.addEntry', 'Add Definition / Abbreviation')}</span>
            </button>
          )}
        </div>
      ) : (
        <div className="space-y-4">
          {definitions.map((def, index) => (
            <div
              key={def.id || `temp-def-${index}`}
              className="bg-slate-950 rounded-xl border border-slate-800 hover:border-slate-700 transition-all"
            >
              {/* Card Header */}
              <div className="flex items-center justify-between px-4 py-2.5 bg-slate-900/50 rounded-t-xl border-b border-slate-800/80 gap-2">
                <div className="flex items-center gap-3">
                  <span className="flex items-center justify-center w-6 h-6 rounded-md bg-indigo-900/50 border border-indigo-700/60 font-mono text-xs font-bold text-indigo-200 shrink-0">
                    {def.sequence_number}
                  </span>
                  <span className="text-xs font-semibold text-slate-200">
                    {def.abbreviation ? `${def.abbreviation} — ` : ''}{def.term_en || def.term_ar || t('sop.definitions.unnamedEntry', 'Untitled Definition')}
                  </span>
                </div>

                {!readOnly && (
                  <div className="flex items-center gap-1">
                    <button
                      type="button"
                      onClick={() => handleMoveUp(index)}
                      disabled={index === 0}
                      title={t('common.moveUp', 'Move up')}
                      className="p-1 text-slate-400 hover:text-slate-200 disabled:opacity-30 transition-colors"
                    >
                      <ArrowUp className="w-3.5 h-3.5" />
                    </button>
                    <button
                      type="button"
                      onClick={() => handleMoveDown(index)}
                      disabled={index === definitions.length - 1}
                      title={t('common.moveDown', 'Move down')}
                      className="p-1 text-slate-400 hover:text-slate-200 disabled:opacity-30 transition-colors"
                    >
                      <ArrowDown className="w-3.5 h-3.5" />
                    </button>
                    <button
                      type="button"
                      onClick={() => handleDuplicateDefinition(index)}
                      title={t('common.duplicate', 'Duplicate')}
                      className="p-1 text-slate-400 hover:text-indigo-300 transition-colors"
                    >
                      <Copy className="w-3.5 h-3.5" />
                    </button>
                    <button
                      type="button"
                      onClick={() => handleDeleteDefinition(index)}
                      title={t('common.delete', 'Delete')}
                      className="p-1 text-slate-400 hover:text-rose-400 transition-colors"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                )}
              </div>

              {/* Card Body */}
              <div className="p-4 space-y-3">
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      {t('sop.definitions.abbreviation', 'Abbreviation / Acronym')}
                    </label>
                    <input
                      type="text"
                      value={def.abbreviation || ''}
                      onChange={(e) => handleUpdateDefinition(index, { abbreviation: e.target.value })}
                      disabled={readOnly}
                      placeholder="e.g. BSA, EHR, BSC"
                      className="w-full px-3 py-1.5 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60 font-mono"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      {t('sop.definitions.termEn', 'Term (EN)')}
                    </label>
                    <input
                      type="text"
                      value={def.term_en || ''}
                      onChange={(e) => handleUpdateDefinition(index, { term_en: e.target.value })}
                      disabled={readOnly}
                      dir="ltr"
                      placeholder="e.g. Body Surface Area"
                      className="w-full px-3 py-1.5 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      {t('sop.definitions.termAr', 'المصطلح (AR)')}
                    </label>
                    <input
                      type="text"
                      value={def.term_ar || ''}
                      onChange={(e) => handleUpdateDefinition(index, { term_ar: e.target.value })}
                      disabled={readOnly}
                      dir="rtl"
                      placeholder="مثال: مساحة سطح الجسم"
                      className="w-full px-3 py-1.5 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60 text-right"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      {t('sop.definitions.definitionEn', 'Definition (EN)')} <span className="text-rose-400">*</span>
                    </label>
                    <textarea
                      rows={2}
                      value={def.definition_en}
                      onChange={(e) => handleUpdateDefinition(index, { definition_en: e.target.value })}
                      disabled={readOnly}
                      dir="ltr"
                      placeholder="Measured or calculated surface of a human body used for accurate chemotherapy dose calculation."
                      className="w-full px-3 py-1.5 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      {t('sop.definitions.definitionAr', 'التعريف (AR)')}
                    </label>
                    <textarea
                      rows={2}
                      value={def.definition_ar || ''}
                      onChange={(e) => handleUpdateDefinition(index, { definition_ar: e.target.value })}
                      disabled={readOnly}
                      dir="rtl"
                      placeholder="المساحة المحسوبة لجسم المريض المستخدمة في احتساب جرعات العلاج الكيماوي بدقة."
                      className="w-full px-3 py-1.5 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60 text-right"
                    />
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
