import { useState } from 'react';
import { useI18n } from '../../i18n/I18nContext';
import type { SopProcedureStep } from '../../lib/policySopApi';
import { 
  Plus, 
  Trash2, 
  ArrowUp, 
  ArrowDown, 
  Copy, 
  ShieldAlert, 
  Clock, 
  FileCheck, 
  GitFork, 
  AlertTriangle,
  HelpCircle
} from 'lucide-react';

interface SopProcedureBuilderProps {
  steps: SopProcedureStep[];
  onChange: (steps: SopProcedureStep[]) => void;
  controls: Array<{ id: string; code: string; title: string }>;
  readOnly?: boolean;
}

export function SopProcedureBuilder({
  steps,
  onChange,
  controls,
  readOnly = false,
}: SopProcedureBuilderProps) {
  const { t } = useI18n();
  const [activeStepIndex, setActiveStepIndex] = useState<number | null>(null);

  const handleAddStep = () => {
    if (readOnly) return;
    const newSeq = steps.length + 1;
    const newStep: SopProcedureStep = {
      sequence_number: newSeq,
      responsible_role: 'Clinical Nurse / Officer',
      action_instruction_en: '',
      action_instruction_ar: '',
      required_control_id: null,
      expected_evidence_record_en: '',
      expected_evidence_record_ar: '',
      timing_sla_en: '',
      timing_sla_ar: '',
      is_decision_point: false,
      decision_criteria_en: '',
      decision_criteria_ar: '',
      criticality: 'medium',
      escalation_trigger_en: '',
      escalation_trigger_ar: '',
      escalation_destination_role: ''
    };
    onChange([...steps, newStep]);
    setActiveStepIndex(steps.length);
  };

  const handleDuplicateStep = (index: number) => {
    if (readOnly) return;
    const target = steps[index];
    const duplicated: SopProcedureStep = {
      ...target,
      id: undefined, // New UUID will be generated by backend
      action_instruction_en: `${target.action_instruction_en} (Copy)`,
      sequence_number: index + 2
    };

    const newSteps = [
      ...steps.slice(0, index + 1),
      duplicated,
      ...steps.slice(index + 1)
    ].map((step, idx) => ({
      ...step,
      sequence_number: idx + 1
    }));

    onChange(newSteps);
    setActiveStepIndex(index + 1);
  };

  const handleDeleteStep = (index: number) => {
    if (readOnly) return;
    const newSteps = steps
      .filter((_, idx) => idx !== index)
      .map((step, idx) => ({
        ...step,
        sequence_number: idx + 1
      }));
    onChange(newSteps);
    if (activeStepIndex === index) {
      setActiveStepIndex(null);
    } else if (activeStepIndex !== null && activeStepIndex > index) {
      setActiveStepIndex(activeStepIndex - 1);
    }
  };

  const handleMoveUp = (index: number) => {
    if (readOnly || index === 0) return;
    const newSteps = [...steps];
    const temp = newSteps[index - 1];
    newSteps[index - 1] = newSteps[index];
    newSteps[index] = temp;

    const resequenced = newSteps.map((step, idx) => ({
      ...step,
      sequence_number: idx + 1
    }));
    onChange(resequenced);
    setActiveStepIndex(index - 1);
  };

  const handleMoveDown = (index: number) => {
    if (readOnly || index === steps.length - 1) return;
    const newSteps = [...steps];
    const temp = newSteps[index + 1];
    newSteps[index + 1] = newSteps[index];
    newSteps[index] = temp;

    const resequenced = newSteps.map((step, idx) => ({
      ...step,
      sequence_number: idx + 1
    }));
    onChange(resequenced);
    setActiveStepIndex(index + 1);
  };

  const handleUpdateStep = (index: number, updates: Partial<SopProcedureStep>) => {
    if (readOnly) return;
    const newSteps = steps.map((step, idx) => {
      if (idx === index) {
        return { ...step, ...updates };
      }
      return step;
    });
    onChange(newSteps);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pb-4 border-b border-slate-800">
        <div>
          <h3 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <span>{t('sop.procedure.title')}</span>
            <span className="px-2 py-0.5 text-xs font-medium rounded bg-indigo-950 text-indigo-300 border border-indigo-800/50">
              {steps.length} {t('sop.stepsCount')}
            </span>
          </h3>
          <p className="text-xs text-slate-400 mt-1">
            {t('sop.procedure.subtitle')}
          </p>
        </div>

        {!readOnly && (
          <button
            type="button"
            onClick={handleAddStep}
            className="inline-flex items-center justify-center gap-2 px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-lg shadow transition-colors active:scale-95 shrink-0"
          >
            <Plus className="w-4 h-4" />
            <span>{t('sop.procedure.addStep')}</span>
          </button>
        )}
      </div>

      {/* Empty State */}
      {steps.length === 0 ? (
        <div className="p-8 text-center bg-slate-900/30 rounded-xl border border-dashed border-slate-800">
          <FileCheck className="w-10 h-10 text-slate-600 mx-auto mb-2 stroke-[1.5]" />
          <p className="text-sm font-medium text-slate-300">{t('sop.procedure.noSteps')}</p>
          <p className="text-xs text-slate-500 mt-1 max-w-md mx-auto">
            {t('sop.procedure.noStepsPrompt')}
          </p>
          {!readOnly && (
            <button
              type="button"
              onClick={handleAddStep}
              className="mt-4 inline-flex items-center gap-2 px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-lg transition-colors"
            >
              <Plus className="w-4 h-4" />
              <span>{t('sop.procedure.addStep')}</span>
            </button>
          )}
        </div>
      ) : (
        <div className="space-y-4">
          {steps.map((step, index) => {
            const isCritical = step.criticality === 'critical' || step.criticality === 'high';
            return (
              <div
                key={step.id || `temp-step-${index}`}
                className={`bg-slate-950 rounded-xl border transition-all ${
                  isCritical 
                    ? 'border-amber-700/50 shadow-sm shadow-amber-950/20' 
                    : 'border-slate-800 hover:border-slate-700'
                }`}
              >
                {/* Step Card Header */}
                <div className="flex items-center justify-between px-4 py-3 bg-slate-900/50 rounded-t-xl border-b border-slate-800/80 gap-2">
                  <div className="flex items-center gap-3">
                    {/* Sequence Badge */}
                    <span className="flex items-center justify-center w-7 h-7 rounded-lg bg-indigo-900/50 border border-indigo-700/60 font-mono text-xs font-bold text-indigo-200 shrink-0">
                      {step.sequence_number}
                    </span>

                    {/* Step Responsible Role */}
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-semibold text-slate-200">
                        {step.responsible_role || t('sop.step.unassignedRole')}
                      </span>
                      {step.is_decision_point && (
                        <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium bg-purple-950/80 text-purple-300 border border-purple-800/50">
                          <GitFork className="w-3 h-3" />
                          <span>{t('sop.step.decisionBadge')}</span>
                        </span>
                      )}
                      {step.criticality === 'critical' && (
                        <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-bold bg-rose-950/80 text-rose-300 border border-rose-800/50">
                          <ShieldAlert className="w-3 h-3 text-rose-400" />
                          <span>{t('sop.step.criticalControlPoint')}</span>
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Ordering & Modification Controls */}
                  {!readOnly && (
                    <div className="flex items-center gap-1">
                      <button
                        type="button"
                        onClick={() => handleMoveUp(index)}
                        disabled={index === 0}
                        title={t('common.moveUp')}
                        className="p-1.5 text-slate-400 hover:text-slate-200 disabled:opacity-30 disabled:hover:text-slate-400 transition-colors"
                      >
                        <ArrowUp className="w-3.5 h-3.5" />
                      </button>
                      <button
                        type="button"
                        onClick={() => handleMoveDown(index)}
                        disabled={index === steps.length - 1}
                        title={t('common.moveDown')}
                        className="p-1.5 text-slate-400 hover:text-slate-200 disabled:opacity-30 disabled:hover:text-slate-400 transition-colors"
                      >
                        <ArrowDown className="w-3.5 h-3.5" />
                      </button>
                      <button
                        type="button"
                        onClick={() => handleDuplicateStep(index)}
                        title={t('common.duplicate')}
                        className="p-1.5 text-slate-400 hover:text-indigo-300 transition-colors"
                      >
                        <Copy className="w-3.5 h-3.5" />
                      </button>
                      <button
                        type="button"
                        onClick={() => handleDeleteStep(index)}
                        title={t('common.delete')}
                        className="p-1.5 text-slate-400 hover:text-rose-400 transition-colors"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  )}
                </div>

                {/* Step Body */}
                <div className="p-4 space-y-4">
                  {/* Responsible Role & Criticality Header Row */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.responsibleRole')} <span className="text-rose-400">*</span>
                      </label>
                      <input
                        type="text"
                        value={step.responsible_role}
                        onChange={(e) => handleUpdateStep(index, { responsible_role: e.target.value })}
                        disabled={readOnly}
                        placeholder={t('sop.step.rolePlaceholder')}
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60"
                      />
                    </div>

                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.criticality')}
                      </label>
                      <select
                        value={step.criticality}
                        onChange={(e) => handleUpdateStep(index, { criticality: e.target.value as any })}
                        disabled={readOnly}
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 focus:outline-none focus:border-indigo-500 disabled:opacity-60"
                      >
                        <option value="low">{t('criticality.low')}</option>
                        <option value="medium">{t('criticality.medium')}</option>
                        <option value="high">{t('criticality.high')}</option>
                        <option value="critical">{t('sop.step.criticalControlPoint')}</option>
                      </select>
                    </div>

                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.requiredControl')}
                      </label>
                      <select
                        value={step.required_control_id || ''}
                        onChange={(e) => handleUpdateStep(index, { required_control_id: e.target.value || null })}
                        disabled={readOnly}
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 focus:outline-none focus:border-indigo-500 disabled:opacity-60"
                      >
                        <option value="">{t('sop.step.noneLinked')}</option>
                        {controls.map((ctrl) => (
                          <option key={ctrl.id} value={ctrl.id}>
                            {ctrl.code} - {ctrl.title}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>

                  {/* Action / Instruction EN & AR */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.instructionEn')} <span className="text-rose-400">*</span>
                      </label>
                      <textarea
                        rows={2}
                        value={step.action_instruction_en}
                        onChange={(e) => handleUpdateStep(index, { action_instruction_en: e.target.value })}
                        disabled={readOnly}
                        dir="ltr"
                        placeholder={t('sop.step.instructionEnPlaceholder')}
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.instructionAr')}
                      </label>
                      <textarea
                        rows={2}
                        value={step.action_instruction_ar || ''}
                        onChange={(e) => handleUpdateStep(index, { action_instruction_ar: e.target.value })}
                        disabled={readOnly}
                        dir="rtl"
                        placeholder={t('sop.step.instructionArPlaceholder')}
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60 text-right"
                      />
                    </div>
                  </div>

                  {/* Expected Evidence & SLA Row */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3">
                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.expectedEvidenceEn')}
                      </label>
                      <input
                        type="text"
                        value={step.expected_evidence_record_en || ''}
                        onChange={(e) => handleUpdateStep(index, { expected_evidence_record_en: e.target.value })}
                        disabled={readOnly}
                        placeholder={t('sop.step.evidenceEnPlaceholder')}
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.expectedEvidenceAr')}
                      </label>
                      <input
                        type="text"
                        value={step.expected_evidence_record_ar || ''}
                        onChange={(e) => handleUpdateStep(index, { expected_evidence_record_ar: e.target.value })}
                        disabled={readOnly}
                        dir="rtl"
                        placeholder={t('sop.step.evidenceArPlaceholder')}
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60 text-right"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.timingSlaEn')}
                      </label>
                      <input
                        type="text"
                        value={step.timing_sla_en || ''}
                        onChange={(e) => handleUpdateStep(index, { timing_sla_en: e.target.value })}
                        disabled={readOnly}
                        placeholder="e.g. Within 15 minutes"
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-slate-300 mb-1">
                        {t('sop.step.timingSlaAr')}
                      </label>
                      <input
                        type="text"
                        value={step.timing_sla_ar || ''}
                        onChange={(e) => handleUpdateStep(index, { timing_sla_ar: e.target.value })}
                        disabled={readOnly}
                        dir="rtl"
                        placeholder="خلال 15 دقيقة"
                        className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 disabled:opacity-60 text-right"
                      />
                    </div>
                  </div>

                  {/* Decision Point & Escalation Section */}
                  <div className="p-3 bg-slate-900/40 rounded-lg border border-slate-800/80 space-y-3">
                    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                      <label className="flex items-center gap-2 text-xs font-medium text-slate-300 cursor-pointer select-none">
                        <input
                          type="checkbox"
                          checked={step.is_decision_point}
                          onChange={(e) => handleUpdateStep(index, { is_decision_point: e.target.checked })}
                          disabled={readOnly}
                          className="rounded border-slate-700 text-indigo-600 focus:ring-0 w-3.5 h-3.5 disabled:opacity-60"
                        />
                        <span>{t('sop.step.isDecisionPoint')}</span>
                      </label>

                      <span className="text-[11px] text-slate-500">
                        {t('sop.step.decisionHint')}
                      </span>
                    </div>

                    {step.is_decision_point && (
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2 border-t border-slate-800/60">
                        <div>
                          <label className="block text-xs font-semibold text-slate-400 mb-1">
                            {t('sop.step.decisionCriteriaEn')}
                          </label>
                          <input
                            type="text"
                            value={step.decision_criteria_en || ''}
                            onChange={(e) => handleUpdateStep(index, { decision_criteria_en: e.target.value })}
                            disabled={readOnly}
                            dir="ltr"
                            placeholder="e.g. If patient temperature >= 38.5C"
                            className="w-full px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
                          />
                        </div>
                        <div>
                          <label className="block text-xs font-semibold text-slate-400 mb-1">
                            {t('sop.step.decisionCriteriaAr')}
                          </label>
                          <input
                            type="text"
                            value={step.decision_criteria_ar || ''}
                            onChange={(e) => handleUpdateStep(index, { decision_criteria_ar: e.target.value })}
                            disabled={readOnly}
                            dir="rtl"
                            placeholder="مثال: إذا كانت درجة حرارة المريض >= 38.5 مئوية"
                            className="w-full px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-slate-100 focus:outline-none focus:border-indigo-500 text-right"
                          />
                        </div>
                      </div>
                    )}

                    {/* Escalation Row */}
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-2 border-t border-slate-800/60">
                      <div>
                        <label className="block text-xs font-semibold text-slate-400 mb-1">
                          {t('sop.step.escalationTriggerEn')}
                        </label>
                        <input
                          type="text"
                          value={step.escalation_trigger_en || ''}
                          onChange={(e) => handleUpdateStep(index, { escalation_trigger_en: e.target.value })}
                          disabled={readOnly}
                          placeholder="e.g. No response in 10 min"
                          className="w-full px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-semibold text-slate-400 mb-1">
                          {t('sop.step.escalationTriggerAr')}
                        </label>
                        <input
                          type="text"
                          value={step.escalation_trigger_ar || ''}
                          onChange={(e) => handleUpdateStep(index, { escalation_trigger_ar: e.target.value })}
                          disabled={readOnly}
                          dir="rtl"
                          placeholder="عدم الاستجابة خلال 10 دقائق"
                          className="w-full px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-slate-100 focus:outline-none focus:border-indigo-500 text-right"
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-semibold text-slate-400 mb-1">
                          {t('sop.step.escalationDestinationRole')}
                        </label>
                        <input
                          type="text"
                          value={step.escalation_destination_role || ''}
                          onChange={(e) => handleUpdateStep(index, { escalation_destination_role: e.target.value })}
                          disabled={readOnly}
                          placeholder="e.g. Senior Consultant / Quality Officer"
                          className="w-full px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
